const authUserController = require("../controllers/userController/authuser.controller");
const productController= require("../controllers/productController/product.controller");
const productDetailsController= require("../controllers/productController/productDetails.controller");
const productSizesController= require("../controllers/productController/productsizes.controller");
const productTagsController= require("../controllers/productController/producttags.controller");
const cartController= require("../controllers/cartController/cart.controller");
const cartDetailsController= require("../controllers/cartController/cartDetails.controller");
const couponController= require("../controllers/couponController/coupons.controller");
const couponUsersController= require("../controllers/couponController/couponUsers.controller");
const deliveryController= require("../controllers/deliveryController/deliveryAddress.controller");
const invoiceController= require("../controllers/invoiceController/invoiceDetails.controller");
const orderController= require("../controllers/orderController/orders.controller");
const orderStatusController= require("../controllers/orderController/orderStatus.controller");
const paymentController= require("../controllers/paymentController/payment.controller");
const tagController= require("../controllers/tagController/tags.controller");
const express = require('express');
const router = express.Router();
router.use('/api/authuser',authUserController);
router.use('/api/product',productController);
router.use('/api/productdetails',productDetailsController);
router.use('/api/productsizes',productSizesController);
router.use('/api/producttags',productTagsController);
router.use('/api/cart',cartController);
router.use('/api/cartdetails',cartDetailsController);
router.use('/api/coupon',couponController);
router.use('/api/couponusers',couponUsersController);
router.use('/api/delivery',deliveryController);
router.use('/api/invoice',invoiceController);
router.use('/api/payment',paymentController);
router.use('/api/order',orderController);
router.use('/api/orderstatus',orderStatusController);
router.use('/api/tags',tagController);

module.exports = router;